name: Checks

on:
  push:
  pull_request:

permissions:
  contents: read

jobs:

  consistency-checks:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Set up Go 1.25
      uses: actions/setup-go@v5
      with:
          go-version: 1.25.x

    - name: OS details
      run: |
          uname -a
          if [ -e /etc/os-release ]; then cat /etc/os-release; fi

    - name: Install packages
      if: ${{ runner.os == 'Linux' }}
      run: |
          sudo apt-get -y install krb5-user libkrb5-dev

    - name: Code format check
      run: ./.github/scripts/gofmt

    - name: Static check
      uses: dominikh/staticcheck-action@v1

    - name: golangci-lint
      uses: golangci/golangci-lint-action@v8
      with:
        version: latest

  basic-tests:
    name: Basic tests
    strategy:
      fail-fast: false
      matrix:
        os: ['ubuntu-latest', 'macos-latest']
        go-version: ['1.24.x', '1.25.x' ]
        krb5-version: ["base", "heimdal"]

    runs-on: ${{ matrix.os }}

    steps:
    - uses: actions/checkout@v4

    - name: Set up Go ${{ matrix.go-version }}
      uses: actions/setup-go@v5
      with:
        go-version: ${{ matrix.go-version }}

    - name: OS details
      run: |
          echo This is Github OS ${{ runner.os }}
          uname -a
          if [ -e /etc/os-release ]; then cat /etc/os-release; fi

    - name: Install Ubuntu MIT packages
      if: ${{ runner.os == 'Linux' && matrix.krb5-version == 'base' }}
      run: |
          sudo apt-get -y install krb5-user libkrb5-dev pkg-config

    - name: Install Ubuntu Heimdal packages
      if: ${{ runner.os == 'Linux' && matrix.krb5-version == 'heimdal' }}
      run: |
          sudo apt-get install -y heimdal-dev pkg-config

    - name: Install MacOS Heimdal packages
      if: ${{ runner.os == 'macOS' && matrix.krb5-version == 'heimdal' }}
      run: |
          brew install heimdal
          echo "PKG_CONFIG_PATH=/opt/homebrew/opt/heimdal/lib/pkgconfig" >>$GITHUB_ENV

    - name: Generate test includes
      run: |
        echo pkgs=$(go list ./... | grep -v /examples/) >> "$GITHUB_ENV"

    - name: Run tests
      run: |
        go clean -cache
        go test  $pkgs -coverprofile=cover.out -covermode=atomic

    - name: Check test coverage
      if: ${{ runner.os == 'Linux' && matrix.krb5-version == 'base' && matrix.go-version == '1.25.x' }}
      uses: jake-scott/go-test-coverage@v1.0.0
      with:
        config: ./.testcoverage.yml
        threshold-total: 80
